language: node_js
node_js: 12
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=personality-insights-livedemo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
before_deploy: npm install -g bx-blue-green
deploy:
- provider: script
  script: bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/personality-insights-nodejs
  skip_cleanup: true
- provider: script
  skip_cleanup: true
  script: npx semantic-release
